### PR TITLE
Merge hotfix-NR-CSV-names into hotfix-NR-data-update

### PR DESCRIPTION
**Pull request by cgettings**
I created a new branch for these changes, but there was already this existing branch. I missed @mmontesanonyc linking to it in issue #7, so I'm going to merge my extra branch into the one created for this purpose, then delete hotfix-NR-CSV-names. Unless this is completely unnecessary, in which case, we can delete hotfix-NR-data-update.

FYI, I had to install hugo-extended to get `serve` to work.

### CODE REVIEW

**Comment by mmontesanonyc** [comment]
Merging these two together is perfect - hotfix-NR-data-update has some changes to the page structure to incorporate that "measurement type" variable that you and Grant worked on a few weeks ago (which ensures that we can express data as more than just Percents!). 

I'll test this a little later on today - thanks!

**Comment by mmontesanonyc** [comment]
Hmm - there are a few things that feel off here - I'm getting, curiously, data that aren't sorted, don't match the tiny preview bar-charts on the report output, and in the indicator details, values that don't match (chart with summary values up top). Haven't had time to dig in and figure out what's off; but one nice and important part, regardless, is that the files are in and rendering! I think we can merge these branches together and then figure out what's up with the data. 

image

**Comment by cgettings** [comment]
That's so weird. How could they be _kinda_ sorted?

**Comment by mmontesanonyc** [comment]
Heh, I'm not sure - initial guesses are somehow conflation with a similar indicator, or different years, but I can't see how we'd wind up with two different years of data (one informing the sort and the other being displayed) in there. 

We also lost the active design data:

image

I'm sure we'll figure this out. I don't have a ton of time over the next couple days to dig into this, but next week is pretty wide open.

**Comment by mmontesanonyc** [comment]
I merged the two; let's keep the work gong on hotfix-NR-data-update

It looks like the individual-indicator files have multiple values for each neighborhood - probably multiple years instead of filtering most recent year:

image

**Comment by cgettings** [comment]
So we just want the most recent year?

**Comment by mmontesanonyc** [comment]
For now, for that file, yup - there are two filetypes, [Indicator].csv and [Indicator}_trend.csv - so for the former, most recent year only. There may be some efficiencies we can work in down the line.

**Comment by mmontesanonyc** [comment]
since NR-CSV-names was merged into NR-data-update, I'm going to delete this branch to keep things tidy.

**Pull request merged**
